import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { faker } from 'meteor/practicalmeteor:faker';
import { _ } from 'meteor/stevezhu:lodash';

import CRIMP from '../imports/settings';
import Messages from '../imports/data/messages';
import Events from '../imports/data/events';
import Categories from '../imports/data/categories';
import Teams from '../imports/data/teams';
import Climbers from '../imports/data/climbers';
import Scores from '../imports/data/scores';
import HelpMe from '../imports/data/helpme';
import ActiveTracker from '../imports/data/activetracker';
import RecentScores from '../imports/data/recentscores';


function baInit() {
  const eve = Events.insert({
    event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    event_name_short: 'NUS-BD Boulderactive',
    time_start: new Date(2016, 5, 16, 9, 0),
    time_end: new Date(2016, 5, 19, 21, 0),
  });

  const umq = Categories.insert({
    category_name: 'U-17 Men Qualifiers',
    acronym: 'UMQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 16, 10, 0),
    time_end: new Date(2016, 5, 16, 11, 0),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'UMQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMQ5',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMQ6',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const nmq = Categories.insert({
    category_name: 'Novice Men Qualifiers',
    acronym: 'NMQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 16, 10),
    time_end: new Date(2016, 5, 16, 16),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'NMQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMQ5',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMQ6',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const uwq = Categories.insert({
    category_name: 'U-17 Women Qualifier',
    acronym: 'UWQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 16, 16, 15),
    time_end: new Date(2016, 5, 16, 17, 15),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'UWQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWQ5',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWQ6',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const nwq = Categories.insert({
    category_name: 'Novice Women Qualifer',
    acronym: 'NWQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 16, 16, 15),
    time_end: new Date(2016, 5, 16, 21),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'NWQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWQ5',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWQ6',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const iwq = Categories.insert({
    category_name: 'Intermediate Women Qualifier',
    acronym: 'IWQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 17, 10, 45),
    time_end: new Date(2016, 5, 17, 12, 30),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'IWQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IWQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IWQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IWQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IWQ5',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const imq = Categories.insert({
    category_name: 'Intermediate Men Qualifier',
    acronym: 'IMQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 17, 13),
    time_end: new Date(2016, 5, 17, 15, 30),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'IMQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IMQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IMQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IMQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IMQ5',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const owq = Categories.insert({
    category_name: 'Open Women Qualifier',
    acronym: 'OWQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 18, 14, 30),
    time_end: new Date(2016, 5, 18, 17),
    score_system: 'TFBb',
    routes: [{
      _id: Random.id(),
      route_name: 'OWQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ5',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ6',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ7',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWQ8',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const omq = Categories.insert({
    category_name: 'Open Men Qualifier',
    acronym: 'OMQ',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 18, 17, 30),
    time_end: new Date(2016, 5, 18, 20),
    score_system: 'TFBb',
    routes: [{
      _id: Random.id(),
      route_name: 'OMQ1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ4',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ5',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ6',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ7',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMQ8',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const oms = Categories.insert({
    category_name: 'Open Men Semi-Final',
    acronym: 'OMS',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 9, 30),
    time_end: new Date(2016, 5, 19, 11, 15),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'OMS1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMS2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMS3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMS4',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const ows = Categories.insert({
    category_name: 'Open Women Semi-Final',
    acronym: 'OWS',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 9, 30),
    time_end: new Date(2016, 5, 19, 11, 15),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'OWS1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWS2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWS3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWS4',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const umf = Categories.insert({
    category_name: 'U-17 Men Final',
    acronym: 'UMF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 11, 45),
    time_end: new Date(2016, 5, 19, 14, 00),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'UMF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UMF3',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const uwf = Categories.insert({
    category_name: 'U-17 Women Final',
    acronym: 'UWF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 11, 45),
    time_end: new Date(2016, 5, 19, 14, 00),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'UWF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'UWF3',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const nmf = Categories.insert({
    category_name: 'Novice Men Final',
    acronym: 'NMF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 11, 45),
    time_end: new Date(2016, 5, 19, 14, 00),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'NMF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NMF3',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const nwf = Categories.insert({
    category_name: 'Novice Women Final',
    acronym: 'NWF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 11, 45),
    time_end: new Date(2016, 5, 19, 14, 00),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'NWF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'NWF3',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const imf = Categories.insert({
    category_name: 'Intermediate Men Final',
    acronym: 'IMF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 14, 30),
    time_end: new Date(2016, 5, 19, 16),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'IMF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IMF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IMF3',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const iwf = Categories.insert({
    category_name: 'Intermediate Women Final',
    acronym: 'IWF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 14, 30),
    time_end: new Date(2016, 5, 19, 16),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'IWF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IWF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'IWF3',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const omf = Categories.insert({
    category_name: 'Open Men Final',
    acronym: 'OMF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 19),
    time_end: new Date(2016, 5, 19, 21),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'OMF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMF3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OMF4',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });

  const owf = Categories.insert({
    category_name: 'Open Women Final',
    acronym: 'OWF',
    is_team_category: false,
    is_score_finalized: false,
    climber_count: 0,
    time_start: new Date(2016, 5, 19, 19),
    time_end: new Date(2016, 5, 19, 21),
    score_system: 'IFSC-Top-Bonus',
    routes: [{
      _id: Random.id(),
      route_name: 'OWF1',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWF2',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWF3',
      score_rules: {},
    }, {
      _id: Random.id(),
      route_name: 'OWF4',
      score_rules: {},
    }],
    event: {
      _id: eve,
      event_name_full: 'NUS - Black Diamond Boulderactive 2016',
    },
  });


  function addClimber(array, gender, catId) {
    _.forEach(array, (c) => {
      const cmb = Climbers.insert({
        gender,
        climber_name: c,
        identity: '',
        affliation: '',
        categories: [],
      });

      Categories.methods.addClimber.call({
        climberId: cmb,
        categoryId: catId,
      });
    });
  }

  const umqClimbers = [
    'Sirapob Jirajaturapak',
    'Muhammad Elparizi Redky',
    'Dylan Woo Wye Lun',
    'Mohamad Shafitri B Mohamed F',
    'Riko Chua',
    'Muhammad Ayman Bin Roslee',
    'Murshid Wahid',
    'Muhammad Hannan Bin Rahmatullah',
    'Muhammad Mahyuddin Bin Mansor',
    'Ardiy Bin Astika',
    'Mohd Shadi Bin Mohd Hannan',
    'Jarrell Soh Jit Kai',
    'Parit Khunboriwarn',
    'Patrick Lawrence Yau Yin Chambers',
    'Jonas Chew',
    'Antasyafy Robby Al Hilmi',
    'Laurens Jaczynski',
    'Chan Matthew Alexander',
    'Dylan Zhi Yang Lau',
    'Kieran Dawson',
    'Teeraphon Boondech',
    'Ethan Teo Rui Hang',
    'Desmond Laja Tan',
    'Isaac Lau Yujie',
    'Karl Breuer',
    'Geniblazo Elijah James',
    'Alex Ho Jia Yue',
    'Tan Bing Qian',
    'Muhamnad Zulfahmi Bin Zulkifli',
    'Naufal Dani Zikry Bin Mohamad Faizal',
    'Raiyan Bin Oani',
    'Syahzyad Syawqie',
    'Baode',
    'Chea Rui Yang',
    'Chan Jingjie',
    'Chow Zi Yang',
    'Ho Jun Wai, Owen',
    'Limkaiwei',
    'Nguyen Loc Truong',
    'Sim Qi Xun',
  ];

  addClimber(umqClimbers, 'M', umq);

  const uwqClimbers = [
    'Byoray Tang Wen Jia',
    'Tiarra Ko',
    'Maria Ulfah Binte Mohammed Jamil',
    'Nurul Maisarah Binti Jaya',
    'Kaylan Yip Kit Yen',
    'Nurul Jannah Bte Mobin',
    'Clarisse Ong Zi Yi',
    'Ayeisha Johnstone',
    'Pannaporn Khunboriwarn',
    'Askia Ashazahra',
    'Iinaas Nuur Ghoni',
    'Adilla Wahyu Alam',
    'Choy Xin Ying',
    'Tanika Birkbeck',
    'Koh Tsi Yee Genevieve',
    'Caelinn O Maoileoin',
    'Ayesha Pointer',
    'Aaliya Vij',
    'Tan Si Ning Amy',
    'Nazeera Mohamed Rizal',
    'Nur Rindianni Mohamad Razli',
    'Chua Min Jing Mint',
    'Jesabel Ng Zi Qing',
    'Intan Ellyana Bte Abdullah Jumali',
    'Chan Pei Yan',
    'Tiu Shin',
    'Lim Li En',
    'Jolyn Neo Jing Wei',
    'Tee Yi Xuan Ally',
    'Swee Yao',
    'Lee Si En',
  ];

  addClimber(uwqClimbers, 'F', uwq);

  const nmqClimbers = [
    'Gary Leon Lai',
    'Aniq Hilman',
    'Luke Chow',
    'Jamus Heng',
    'Marcus Tan Xuan Han',
    'Nasrul Hadi B Said',
    'Nicolas Lecomte',
    'Aloysius Yap Jun Fu',
    'Gabriel Ignatius Lee Kee Hon',
    'Ho Jun Wen Brian',
    'Huang Xinyan',
    'Koh Guo Feng',
    'Macalister Tan',
    'Mohammed Izhak@Hein Htet',
    'Sim Rui Hong Edwin',
    'Wong Chun Xi',
    'Yuen Jun Heng Derek',
    'Chia Yi Ching',
    'Timothy Tan Aum You',
    'Melchizedek Jeshua Jitam',
    'Samuel Chung Shie Yu',
    'Hans Breuer',
    'Sayyid Mohammad Farid B S A A',
    'Theeraphon Cherdchuvitayasil',
    'Jonathan Chua Hsien Wen',
    'Clement Chan Jin Liang',
    'Muhd Nur Adlee Bin Margono',
    'Muhammad Hafiz Bin Kamsani',
    'Faris Bin Nahar Azmi',
    'John Wong Jing Qian',
    'Mohammad Amiri Bin Mohd Hadri',
    'Raja Tsaqif Helmi',
    'Edwin Chong Yong Sheng',
    'Muhammad Hirzan Bin Rahmat',
    'Lieu Shi Yang',
    'Alexander Lee Shi Wei',
    'Dave Dexter Tan',
    'Imaduddin Haetami',
    'Teo Jun Wei',
    'Ian Yip Shao-Hern',
    'Muhammad Bin Zulkarnain',
    'Ryan Chiong Ban Hee',
    'Tan Jia Liang Jeremy',
    'Tan Tse How Jason',
    'Colin Lai Jun Hao',
    'Goh Wei Jia',
    'Justin Ho Jin Kiat',
    'León Lim Jian Ying',
    'Raedi Haizer Bin Sidik',
    'Yeap Wen Hao Brian',
    'Yeo Wen Bin',
    'Alfy Ramdzan',
    'Muhammad Izzuddin Bin Mahamad Husin',
    'Muhammad Abdul Haq Bin Mansor',
    'Aloysius Lim Bing Hong',
    'Arif Solihin',
    'Chai Teng Ping',
    'Chin Yen Chai',
    'Guan Zhi Min',
    'Jeremy Ng Jia Jun',
    'Justin Tan Kai Zhong',
    'Kenneth Lim Wen Khang',
    'Koh Aik Leng',
    'Lee Loon Rong',
    'Lim Yi Da',
    'Marcus Ong Qin Wen',
    'Muhammad Haiqal Bin Mahbod',
    'Nur Syafiq Bin Suhaimi',
    'Ong Xuanwei',
    'Ryofred Tang',
    'Mohamad Fareez Bin Mohd Poot',
    'Bernard Mui',
    'Abdillah Hafiz Zulkifly',
    'Abdul Qaiyum Lee Bin Abdul Aziz',
    'Amar Hassan Bin Mohamad Kamal',
    'Dylan Ng Keah Hnng',
    'Joseph Pang Zhi Wei',
    'Li Yang Yue, Edson',
    'Lim Kia Wee, Noah',
    'Stefan Choo Bin Hao',
    'Tan Jin Quan Jared',
    'Teo Sia Yong Amos',
    'Victor Lim Wei Jie',
    'Chng Jia Yang',
    'Justin Tan Jia Jun',
    'Suhartono Gunawan',
    'Mohd Fikrilamin Bin Hanapiah',
    'Jonathan Benjamin Seror',
    'Louise De Guzman',
    'Ho Zheng Feng Justin',
    'Safiy Suherman Shah',
    'Tan Tien Sern',
    'V Livesh Kumar',
    'Chai Zi Jun',
    'Gan Jin Zhou',
    'Gavin Leong Zee Kin',
    'Ho Khee Wei',
    'Ho Peng Han',
    'Kwan Qing Zhong Emmanuel',
    'Lim Zhi Yuan',
    'Louis Goh Yuan Yu',
    'Oh Chunguan Darius',
    'Tan Zhi Kai',
    'Theodore Tan Xu Yang',
    'Wong Wei Qi',
    'Julian Yap Hua Wei',
    'Lim Chen',
    'Lin Jun Rong',
    'Liu Yiliu',
    'Mok Siew Ing',
    'Owen Yip Jing En',
    'Ziv Low En Hao',
    'Muhammad Andrika Bin Haron',
    'Abdul Qadir Bin Mohd Kassim',
    'Alvin Ngow Feng Hao',
    'Chua Jian Ming',
    'Kenny Sze Zheng Jie',
    'Muhammad Syahmi Bin Amiruddin Zanki',
    'Sin Weng Kit Gregory',
    'Willis Tee Teo Kian',
    'Wong Yien',
    'Zai Shihao',
    'Gordon Teo Wei Kiat',
    'Delson Ong',
    'Goh Sheng Ze Marcus',
    'Hia Zhi Wen',
    'Ng Jun Xiang',
    'Yip Hao Zheng',
    'Tang Yi Hao Daryl',
    'Joshua Lim Zhi Qun',
    'T Ramganesh',
    'Lim Heng Long Nicholas',
    'Muhammad Amin Bin Abdul Jalil',
    'Luke Goh Wen Bin',
    'Lee Guo Zhang',
    'Benedict Tan Shan Wen',
    'Yap Joon Loong',
    'Shakir Bin Ab Razak',
    'Khoo Tsair Shieh',
    'Lim Mun Cheong Edmund',
    'Austen Pointer',
    'Malcolm Tan',
    'Noel Koh',
    'R Sudakar',
    'Tay Hui Hong',
    'Arpith Koshy',
    'Bhone Myat Gon',
    'Leong Yu Bin Adrian',
    'Mohammad Alif Daffa',
    'Xu Jiaming',
    'Brian Oh Zhen Guang',
    'Chew Jian Howe',
    'Ong Wei Chin',
    'Jonathan Lee Cheng Juan',
    'Muhammad Shafiq B Ninaba',
    'Ng Ying Elois',
    'Ryne Tan Chun Li',
    'Cavan Soon',
    'Danial Hafiz Bin Muhammed Nafis',
    'Erfan Khairy Bin Hanafi',
    'Hoo Bing Xu',
    'Navarro John Christopher L',
    'Ananta Ghale',
    'Jereme Chong',
    'Xu Jun Feng Amos',
    'Low Hao Hwee Jefferson',
    'Tham Chin Siong',
    'Wee Jiawei Benedict',
    'Choy Ming Han Nicholas',
    'Eh Zhi Hao Dion',
    'Glenn Ng',
    'Song Wen Yang Jonathan',
    'Syafiq Firdaus',
    'Tan Qi Yuan',
    'Wong Teng Fon',
    'Benedict Choi Kok Weng',
    'Faizal Jasmuri',
    'Jerry Heng',
    'Keong Ze Yi, Gilbert',
    'Lawrence Ho Sheng Jin',
    'Muhammad Ilman Fahmi',
    'Muhammad Zaki Bin Mohammad Bakri',
    'Shaun Pang Jie Hui',
    'Ang Wei Heng Wayne',
    'Amos Wong',
    'Szeto Hao Xuan Louis',
    'Teo Wee Meng',
    'Bryan Khoo Chin How',
    'Lim Fang Wei',
    'Lim Tze Hao',
    'Mark Angelo Manacsa Pacheco',
    'Tew Weibin',
    'Mohd Taufiq Bin Aswad',
    'Ng Leng Boon',
    'Muhammad Irfan B Hajis',
    'Matthew Tan Hin Kai',
    'Alamsyah Cahya Cakradiningrat',
    'Chua Rui Xiang',
    'Damien Ho',
    'Gan Jin Jye',
    'Glen Choo Bin Zhi',
    'Jared Mok Shi Jie',
    'Shaun Phua Zong You',
    'Stanley Goh Qi Ming',
    'Yeung Long Yu',
    'Kim Han',
    'Chua Chong Yi',
    'Muhammad Faris Bin Mohamad Kamal',
    'Toh Soon Ching',
    'Marcus Quek Yew Min',
    'Ronnie Yeoh',
    'Nicholas Han Min Siew',
    'Chew Yu Jonathan',
    'Chong Ee Jin',
    'Chua Zhengshen Ryan',
    'Darren Lim Jun Liang',
    'Foo Zhong Yu Aaron',
    'Jack Chong Huai Jie',
    'Jerome Chew',
    'Loy Xing Kang',
    'Goh Yi Ern',
    'Reuben Chay Ser Zhe',
    'Soon Xiang Yan',
    'Tan Pin Ray',
    'Hadi Bin Alwi',
    'Sim Qi Xuan',
    'Wong Sung Yui, Keith',
    'Zachary Allen Vincent',
  ];

  addClimber(nmqClimbers, 'M', nmq);

  const nwqClimbers = [
    'Chin Kang Yi',
    'Erma',
    'Mallika Tan Hui Juann',
    'Tan Sui Wen Talitha',
    'Amelia-Jane Tan Fang Hui',
    'Letitia Ng Huey Ern',
    'Shayn Chan',
    'Tan Jia Yin',
    'Teo Kai Lin Effie',
    'Amirah Hanif',
    'Syarifah Qamarina Bte Syed Ali Aledroos',
    'Azyyati Farisah Binti Abdul Aziz',
    'Lee Su Xian Sandra',
    'Farhana Abdul Wahab',
    'Hilary Armstrong',
    'Chloe Ng Xin Yi',
    'De Cotta Stephanie Frances',
    'Emily Megan Lim',
    'Eunice Poon Yan Ning',
    'Joelle Chan Mei Si',
    'Lee Les Ee',
    'Mun Kye-Lynn Shanna',
    'Pek Lin Lynn',
    'Shannen Koh',
    'Shee Fang Ling',
    'Sheryl Poh Jing Wen',
    'Farah Nasuha Binti Mohd Yusof',
    'Hasmarliah Binte Hassan',
    'Nur Afiqah Bte Mohamad Dahlan',
    'Roxanne Then',
    'Soon Siqi Felicia',
    'Samantha Chung Shie Xuan',
    'Low Yi Ru Jess',
    'Leong Yik Sheng',
    'Li Xinning',
    'Neo Rui Ling Wendi',
    'Pang Shi Ning',
    'Adelia Grace Wee',
    'Chin Yuin Yih',
    'Leong Huiyu',
    'Liau Min Yen',
    'Lim Chen Yue Sabrina',
    'Loi Si Ling',
    'Low Hui Ying Edinna',
    'Wong Chun Hui Sharmaine',
    'Woon Hui Qi',
    'Wong Xin Hui',
    'Diane Chong Min',
    'Goh Min Rui',
    'Jamaine Lee Xiao Xuan',
    'Leow Hui Lin',
    'Ngiam Ze Hui',
    'Nikole Pang',
    'Quek Lee Min Elizabeth',
    'Sylvian Lim Jing Hui',
    'Tan Yi Leng',
    'Too Karl Jun',
    'Vanessa Teo Hui Yu',
    'Wang Wei',
    'Wee Rongxuan',
    'Zhang Jinghan',
    'Song Shi Ling',
    'Menon Allison Frances',
    'Gina Quek Soik Leng',
    'Ching Sheau Rong',
    'Elizabeth Marie Chai Sih Min',
    'Goh Ching Wun',
    'Hannah Martens',
    'Nelyn Ang Jingyi',
    'Neo Wei Ni',
    'Sng Valerie',
    'Yap Hsin Chen',
    'Yeo Jia Xuan, Danielle',
    'Lee Siew Chen',
    'Kelly Ann Chia Wen Ting',
    'Lim Jae-En Marian',
    'Seah Jessie',
    'Wong Rou Xuan',
    'Noor Jannah Ahmad Hakim',
    'Ang Zheng Fang',
    'Heather Low Si Yan',
    'Lisa Lim Shi Mei',
    'Yan Chonghui',
    'Chia Xin Yin',
    'Emelynn Siah Si Hui',
    'Chua Jia Yin',
    'Eliz Tan Shu Chi',
    'Loh Yi Zhen',
    'Ng An Xin',
    'Seah Cheng Li, Joan',
    'Teo Ann Gie',
    'Joyce Lee Yun Wen',
    'Lim Vanessa Xin-Ying',
    'Sheryl Long Shi Xuan',
    'Hazel Rodrigues',
    'Lee Shiew Mee',
    'Ng Wee Leng Jaslyn',
    'Lynx Jamina Samson',
    'Chan Mei Qi Valerie',
    'Elnatureq Rojoy Gan',
    'Brena Cheong',
    'Hannah Low Wan Ting',
    'Rebecca Low Wan Ying',
    'Leila Fabienne Fuerst',
    'Heather Elizabeth Armstrong',
    'Koh Jian Jia',
    'Fei Cui Overbeel',
    'Natalie Lim Min',
    'Yong Shu Yi, Angeline',
    'Gaelmaine Hoong Yu Heng',
    'Teo Hui Qing Jamie',
  ];

  addClimber(nwqClimbers, 'F', nwq);

  const iwqClimbers = [
    'Leong Yuan Ting, Grace',
    'Thong Weng Yee',
    'Nur Diyana Bte Mohammad Sapri',
    'Nurul Ashikkin',
    'Nicole Liz Ng Yun',
    'Fairuz Binte Omar',
    'Janelle Khoo Xuan Ling',
    'Yau Ding Hua Tricia',
    'Kaely Hoong',
    'Lian Ying Xuan Stacy',
    'Loh Yan Zoey',
    'Intan Syazwani Bte Ja\'Afar',
    'Lim Xin Yi',
    'Siti Shabirah Binte Abu Talib',
    'Nur Diyana Binte Mohamed Sani',
    'Nur Zakirah Bte Khameed',
    'Tan Jia Qi Joyce',
    'Celine Josephine Foo',
    'Florence Loy Ru Yan',
    'Long Yiling Angelyn',
    'Trier Lau',
    'Chin Yuin Yih',
    'Jasmine Chua Li Xian',
    'Kimberly Tan Hwei-Min',
    'Ng Sze Min Rebecca',
    'Quintessence Liu',
    'Tan Hui Lin',
    'Theresa Yong',
    'Yap Si Hui',
    'Wong Yi Xin',
    'Goh Ai Ting',
    'Loh Wan Ling',
    'Yap Hua En Elyse',
    'Chen Fangxian',
    'Irni Susiyanti Bte Jamal',
    'Mariah Batriyisa',
    'Selina Chew Yuet Ling',
    'Dian Desima',
    'Kharisma Ragil Rakasiwi',
    'Putri Larasati',
    'Koh Siew Yi',
    'Lauriane C. Cossette',
    'Alicia Koh',
    'Thio Jing Ling Melodie',
    'Vetra Leow Jing Xuan',
    'Gwen Pang Ying Qi',
    'Nicole Teo Sue Hwee',
  ];

  addClimber(iwqClimbers, 'F', iwq);

  const imqClimbers = [
    'Chong Jia Zhi',
    'Louis-Bernard Carcouet',
    'Tay Yong Sheng',
    'Lio Man Wai',
    'Low Yang Kai (Zac)',
    'Chiak Hui Ming',
    'Chiew Ru Bin',
    'Jeremy Wong Wei Shun',
    'Ryan Tay Eng Ming',
    'Ken Seah',
    'Hiroki Tanaka',
    'Brandon Goh',
    'Cheng Jiamin Dennis',
    'Lim Jun Yiu',
    'Chester Tee Han Jun',
    'Dave Dexter Tan',
    'Tong Jun Jie',
    'Adisalsyahputra',
    'Chua Soon Kiat Jonathan',
    'Daryl Tan',
    'Ferran Tan',
    'Joshua Ko Ying Hou',
    'Lam Mun Yuan',
    'León Lim Jian Ying',
    'Lim Zheng Wei',
    'Tan Jenn Sern Gabriel',
    'Poh Wen Qiang Samuel',
    'Yab Seth',
    'Vincent Wong',
    'Barath S/O Salarajoo',
    'Keith Ang',
    'Jerry Cheong Xian Yang',
    'Chew Ken Yu, Zenedine',
    'Nichol Tomas',
    'Benedict Tan Shan Wen',
    'Yap Joon Loong',
    'Ronnie Yeoh',
    'Jhon Jhon Washington Jusay',
    'Aaron Poh',
    'Cheng Weijing',
    'Lai Yong Liang',
    'Thang Yong Xuan',
    'Robin Bryan',
    'Brandon Gwee Jin Ern',
    'Joshua Suson',
    'Paul Eli Suson',
    'Muhammad Iqbal Kamran',
    'Muhammad Elparizi Redky',
    'Muhammad Ustaza',
    'Gilang Wahyu Perdana',
    'Tan Qian Long, Joshua',
    'Heng Zeng Kai',
    'Eldonyeo',
    'Boaz Teo Sing Hao',
    'Adly Hakim Bin Nasdian',
    'Caleb Choy',
    'Karl Stanley Matthew Dias',
    'Miguel Gervasio',
    'Rizki Yusuf',
    'Iqmal',
    'Abdul Rahman Bin Ramlan',
    'Mohamed Syafiq Bin Mohamed Alipah',
    'Mohd Izzat Bin Mohd Shokor',
    'Muhammad Feroz Bin Muhammad Shaffarudin',
    'Haziq Darajit',
    'Khairul Ikhwan',
    'Muhammad Azli Bin Jaffar',
    'Khairul Asyraf Khan Surattee',
    'Achmad Tegar Prasojo',
    'Muhammad Zulhilmi Bin Mohd Zain',
    'Muhammad Munawar',
    'Sharul Hazman',
  ];

  addClimber(imqClimbers, 'M', imq);

  const owqClimbers = [
    'Nadya Putri Virgita',
    'Vanessa Teng Si Yinn',
    'Ngo Hoe Tuan Audrey',
    'Rachel Lee Shiyi',
    'Verosil Patrice Claire Bayo',
    'Foong Wei Ling',
    'Debbie Tan Zi Jing',
    'Samantha Tan',
    'Alicia Chow Jia Hui',
    'Dayna Hui Su-En',
    'Chua Sheu Wen Janice',
    'Foo Yee Lin Jovin',
    'Lim Janice',
    'Tan Juanmin',
    'Teo Su Fern',
    'Charmaine Lai Zi Xian',
    'Debbie Neo Eng Tin',
    'Pankeaw Plypoolsup',
    'Pratthana Raksachat',
    'Wild Baco Achmad',
    'Fitri Hartani',
    'Dhorifatus Syafiiyah',
    'Dian Novitasari',
    'Lim Peishan',
    'Janet Miao',
    'Tan Shi Hui',
    'Xu Liting',
    'Felicia Lim',
    'Nova Bina Wardani',
    'Novi Cahya Wardani',
    'Liana Nicole G. Mora',
    'Judith Sim',
    'Iris Lee Wee Teng',
    'Choy Jian Ning',
    'Farah Hanisah Bte Mukhlis Chan',
    'Otgonbayar Uyanga',
    'Rosalyn Charlotte Blake',
    'Lynnette Koh',
    'Deryl Ng Wei',
    'Pannaporn Khunboriwarn',
    'Betti Nawafatus Yoga Nita',
    'Janna Tee Jiahui',
    'Ujiayu Sukmandiri',
    'Salsabila',
    'Siti Robiah Adawiyah',
    'Widia Fujiyanti',
  ];

  addClimber(owqClimbers, 'F', owq);

  const omqClimbers = [
    'Randy Yeo Renyi',
    'Chua Renming Dennis',
    'Lee Guo An',
    'Koucai Tan',
    'Akid \'Ammar',
    'Ryan Yeo',
    'Verosil Gerald Bayo',
    'Paul Justin',
    'Albrecht Delft B. Pagaduan',
    'Khairul Hafiz Bin Abu Hassan',
    'Syafie Zolkiple',
    'Justin Goh Kheng Zhong',
    'Shun Kaido',
    'Yoong Wei Theng',
    'Jamal Al Hadad',
    'Panupon Boonprakob',
    'Jhon Jhon Washington Jusay',
    'Ng Jun Loong Aloysius',
    'Ron Ho',
    'Yu Jie Hui',
    'Khairul Asyraf Khan Surattee',
    'Justin Yang',
    'Jan Joseph Suson',
    'Thatthana Raksachat',
    'Khoirul Anam',
    'Eric Ng Yi Xu',
    'Goh Boon Hwee Ryan',
    'David Leo Agustin',
    'Tay Kuan Liang',
    'Muhammad Hilman Bin Haron',
    'Iqmal',
    'Angga Cahya',
    'Muhammad Ustaza',
    'Haroz Foo Xiu Quan',
    'Ahmad Yani',
    'Ismail Ramadhani',
    'Emmanuel Ryan Paul',
    'Phan Shi Yu',
    'Tan Aaron',
    'Lee Hsin Chong',
    'Daryl Tan',
    'Guo Jingyang',
    'Khairul Ikhwan',
    'Lam Mun Yuan',
    'Sean Yew',
    'Azli Jaffar',
    'Saw Jhen Jin',
    'Adisal Tsjung',
    'Shannon Xyrus',
    'Bryan Amias Pillai',
    'Chua Yi Xiong',
    'Fatchur Roji',
    'Abu Dzar Yulianto',
    'Bim Sigrid',
    'Ponti Hardiyanto',
    'Riki Kiswani',
    'Adil Bin Azmoon',
    'Bronson Wee',
    'Hakeem Kasban',
    'Kenneth Chua',
    'Gavin Yong',
    'Muhammad Elparizi Redky',
    'Chew Yi Jie Jader',
    'Izmir Hakim',
    'Mr.Winai Ruangrit',
    'Ku Muhamad Faridhwan Bin Ku Aziz',
    'Abdul Qayum Bin Abd Jalani',
    'Muhammad Taqiuddin Bin Mohd Zulkifli',
    'Lok Wan Tong',
    'Haziq Darajit',
    'Mohammad Ashraf Bin Mohammad Sapri',
    'Adriel Choo',
    'Mora, Iman Lorenzo G',
    'Parit Khunboriwarn',
    'Jonathan Feleo',
    'Jose Mari Cortes Jr.',
    'Kenneth Lim Yong Jie',
    'Marcus Yeo',
    'Boaz Teo Sing Hao',
    'Chan Chong Kiat Mark',
    'Koh Zher Yeow Jay',
    'Aan Aviansyah',
    'Eka Bayu Prabowo',
    'Meichi Narasaki',
  ];

  addClimber(omqClimbers, 'M', omq);
}

Meteor.methods({
  baInit: () => {
    baInit();
  },
});
