<?php
$category='AMF';	//define category
date_default_timezone_set('Asia/Singapore');
$date = getdate();
include('includes/header.php');
include('includes/activeClimber.php')
?>

<section class="climberScores container"><div class="scoreHeader clearfix"><h1>AUC Men Finals</h1><h2>Live Scores</h2><span class="c_top">Top</span><span class="c_bonus">Bonus</span></div>

<div class="climber clearfix" id="rank1"><div id="AM201"><span class="c_rank">1</span><span class="c_id">AM201</span><h3 class="c_name">Finalist 01</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank2"><div id="AM202"><span class="c_rank">2</span><span class="c_id">AM202</span><h3 class="c_name">Finalist 02</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank3"><div id="AM203"><span class="c_rank">3</span><span class="c_id">AM203</span><h3 class="c_name">Finalist 03</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank4"><div id="AM204"><span class="c_rank">4</span><span class="c_id">AM204</span><h3 class="c_name">Finalist 04</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank5"><div id="AM205"><span class="c_rank">5</span><span class="c_id">AM205</span><h3 class="c_name">Finalist 05</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank6"><div id="AM206"><span class="c_rank">6</span><span class="c_id">AM206</span><h3 class="c_name">Finalist 06</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank7"><div id="AM207"><span class="c_rank">7</span><span class="c_id">AM207</span><h3 class="c_name">Finalist 07</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank8"><div id="AM208"><span class="c_rank">8</span><span class="c_id">AM208</span><h3 class="c_name">Finalist 08</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank9"><div id="AM209"><span class="c_rank">9</span><span class="c_id">AM209</span><h3 class="c_name">Finalist 09</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank10"><div id="AM210"><span class="c_rank">10</span><span class="c_id">AM210</span><h3 class="c_name">Finalist 10</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank11"><div id="AM211"><span class="c_rank">11</span><span class="c_id">AM211</span><h3 class="c_name">Finalist 11</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank12"><div id="AM212"><span class="c_rank">12</span><span class="c_id">AM212</span><h3 class="c_name">Finalist 12</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank13"><div id="AM213"><span class="c_rank">13</span><span class="c_id">AM213</span><h3 class="c_name">Finalist 13</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank14"><div id="AM214"><span class="c_rank">14</span><span class="c_id">AM214</span><h3 class="c_name">Finalist 14</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank15"><div id="AM215"><span class="c_rank">15</span><span class="c_id">AM215</span><h3 class="c_name">Finalist 15</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

</section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section><?php include('includes/footer.php'); ?>