<?php
$category='IWF';	//define category
date_default_timezone_set('Asia/Singapore');
$date = getdate();
include('includes/header.php');
include('includes/activeClimber.php')
?>

<section class="climberScores container"><div class="scoreHeader clearfix"><h1>Intermediate Women Finals</h1><h2>Live Scores</h2><span class="c_top">Top</span><span class="c_bonus">Bonus</span></div>

<div class="climber clearfix" id="rank1"><div id="IW101"><span class="c_rank">1</span><span class="c_id">IW101</span><h3 class="c_name">Finalist 01</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank2"><div id="IW102"><span class="c_rank">2</span><span class="c_id">IW102</span><h3 class="c_name">Finalist 02</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank3"><div id="IW103"><span class="c_rank">3</span><span class="c_id">IW103</span><h3 class="c_name">Finalist 03</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank4"><div id="IW104"><span class="c_rank">4</span><span class="c_id">IW104</span><h3 class="c_name">Finalist 04</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank5"><div id="IW105"><span class="c_rank">5</span><span class="c_id">IW105</span><h3 class="c_name">Finalist 05</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank6"><div id="IW106"><span class="c_rank">6</span><span class="c_id">IW106</span><h3 class="c_name">Finalist 06</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank7"><div id="IW107"><span class="c_rank">7</span><span class="c_id">IW107</span><h3 class="c_name">Finalist 07</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank8"><div id="IW108"><span class="c_rank">8</span><span class="c_id">IW108</span><h3 class="c_name">Finalist 08</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank9"><div id="IW109"><span class="c_rank">9</span><span class="c_id">IW109</span><h3 class="c_name">Finalist 09</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank10"><div id="IW110"><span class="c_rank">10</span><span class="c_id">IW110</span><h3 class="c_name">Finalist 10</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank11"><div id="IW111"><span class="c_rank">11</span><span class="c_id">IW111</span><h3 class="c_name">Finalist 11</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank12"><div id="IW112"><span class="c_rank">12</span><span class="c_id">IW112</span><h3 class="c_name">Finalist 12</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank13"><div id="IW113"><span class="c_rank">13</span><span class="c_id">IW113</span><h3 class="c_name">Finalist 13</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank14"><div id="IW114"><span class="c_rank">14</span><span class="c_id">IW114</span><h3 class="c_name">Finalist 14</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank15"><div id="IW115"><span class="c_rank">15</span><span class="c_id">IW115</span><h3 class="c_name">Finalist 15</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

</section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section><?php include('includes/footer.php'); ?>