<?php
$category='OWQ';	//define category
date_default_timezone_set('Asia/Singapore');
$date = getdate();
include('includes/header.php');
include('includes/activeClimber.php')
?>

<section class="climberScores container"><div class="scoreHeader clearfix"><h1>Open Women Qualifiers</h1><h2>Live Scores</h2><span class="c_top">Top</span><span class="c_bonus">Bonus</span></div>

<div class="climber clearfix" id="rank1"><div id="OW001"><span class="c_rank">1</span><span class="c_id">OW001</span><h3 class="c_name">Ashley Tong Pei Yeng</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank2"><div id="OW002"><span class="c_rank">2</span><span class="c_id">OW002</span><h3 class="c_name">Doris Lin</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank3"><div id="OW003"><span class="c_rank">3</span><span class="c_id">OW003</span><h3 class="c_name">Lynnette Koh</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank4"><div id="OW004"><span class="c_rank">4</span><span class="c_id">OW004</span><h3 class="c_name">Xu Liting</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank5"><div id="OW005"><span class="c_rank">5</span><span class="c_id">OW005</span><h3 class="c_name">Tan Shi Hui</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank6"><div id="OW006"><span class="c_rank">6</span><span class="c_id">OW006</span><h3 class="c_name">Janice Ng Li</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank7"><div id="OW007"><span class="c_rank">7</span><span class="c_id">OW007</span><h3 class="c_name">Vanessa Teng</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank8"><div id="OW008"><span class="c_rank">8</span><span class="c_id">OW008</span><h3 class="c_name">Felicia Lim Wei Sze</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank9"><div id="OW009"><span class="c_rank">9</span><span class="c_id">OW009</span><h3 class="c_name">Judith Sim</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank10"><div id="OW010"><span class="c_rank">10</span><span class="c_id">OW010</span><h3 class="c_name">Janet Miao</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank11"><div id="OW011"><span class="c_rank">11</span><span class="c_id">OW011</span><h3 class="c_name">Foong Wei Ling</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank12"><div id="OW012"><span class="c_rank">12</span><span class="c_id">OW012</span><h3 class="c_name">Tan Li Yin Suzanna</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank13"><div id="OW013"><span class="c_rank">13</span><span class="c_id">OW013</span><h3 class="c_name">Deryl Ng Wei</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank14"><div id="OW014"><span class="c_rank">14</span><span class="c_id">OW014</span><h3 class="c_name">Lim Li Ling</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank15"><div id="OW015"><span class="c_rank">15</span><span class="c_id">OW015</span><h3 class="c_name">Pamela Aw Yong Wei Yi</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank16"><div id="OW016"><span class="c_rank">16</span><span class="c_id">OW016</span><h3 class="c_name">Verosil Patrice Claire Bayo</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank17"><div id="OW017"><span class="c_rank">17</span><span class="c_id">OW017</span><h3 class="c_name">Charmaine Lai</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank18"><div id="OW018"><span class="c_rank">18</span><span class="c_id">OW018</span><h3 class="c_name">Zhang Binbin</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank19"><div id="OW019"><span class="c_rank">19</span><span class="c_id">OW019</span><h3 class="c_name">Iris Lee Wee Teng</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank20"><div id="OW020"><span class="c_rank">20</span><span class="c_id">OW020</span><h3 class="c_name">Sean Nicholas</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank21"><div id="OW021"><span class="c_rank">21</span><span class="c_id">OW021</span><h3 class="c_name">Zhang Wenxi</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank22"><div id="OW022"><span class="c_rank">22</span><span class="c_id">OW022</span><h3 class="c_name">Esther Lee</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank23"><div id="OW023"><span class="c_rank">23</span><span class="c_id">OW023</span><h3 class="c_name">Debbie Tan Zi Jing</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank24"><div id="OW024"><span class="c_rank">24</span><span class="c_id">OW024</span><h3 class="c_name">Farah Hanisah Chan</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank25"><div id="OW025"><span class="c_rank">25</span><span class="c_id">OW025</span><h3 class="c_name">Nicolea Edwards</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank26"><div id="OW026"><span class="c_rank">26</span><span class="c_id">OW026</span><h3 class="c_name">Puntarika Tunyavanich</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank27"><div id="OW027"><span class="c_rank">27</span><span class="c_id">OW027</span><h3 class="c_name">Susanti Arpiyah</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank28"><div id="OW028"><span class="c_rank">28</span><span class="c_id">OW028</span><h3 class="c_name">Ernawati</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank29"><div id="OW029"><span class="c_rank">29</span><span class="c_id">OW029</span><h3 class="c_name">Harini</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank30"><div id="OW030"><span class="c_rank">30</span><span class="c_id">OW030</span><h3 class="c_name">Tan Jiie Yi (Trix)</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank31"><div id="OW031"><span class="c_rank">31</span><span class="c_id">OW031</span><h3 class="c_name">Reserved 01</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank32"><div id="OW032"><span class="c_rank">32</span><span class="c_id">OW032</span><h3 class="c_name">Reserved 02</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank33"><div id="OW033"><span class="c_rank">33</span><span class="c_id">OW033</span><h3 class="c_name">Reserved 03</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank34"><div id="OW034"><span class="c_rank">34</span><span class="c_id">OW034</span><h3 class="c_name">Reserved 04</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank35"><div id="OW035"><span class="c_rank">35</span><span class="c_id">OW035</span><h3 class="c_name">Reserved 05</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank36"><div id="OW036"><span class="c_rank">36</span><span class="c_id">OW036</span><h3 class="c_name">Reserved 06</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank37"><div id="OW037"><span class="c_rank">37</span><span class="c_id">OW037</span><h3 class="c_name">Reserved 07</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank38"><div id="OW038"><span class="c_rank">38</span><span class="c_id">OW038</span><h3 class="c_name">Reserved 08</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank39"><div id="OW039"><span class="c_rank">39</span><span class="c_id">OW039</span><h3 class="c_name">Reserved 09</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank40"><div id="OW040"><span class="c_rank">40</span><span class="c_id">OW040</span><h3 class="c_name">Reserved 10</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

</section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section></section><?php include('includes/footer.php'); ?>