<?php
$category='UWF';	//define category
date_default_timezone_set('Asia/Singapore');
$date = getdate();
include('includes/header.php');
include('includes/activeClimber.php')
?>

<section class="climberScores container"><div class="scoreHeader clearfix"><h1>U17 Women Finals</h1><h2>Live Scores</h2><span class="c_top">Top</span><span class="c_bonus">Bonus</span></div>

<div class="climber clearfix" id="rank1"><div id="UW101"><span class="c_rank">1</span><span class="c_id">UW101</span><h3 class="c_name">Finalist 01</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank2"><div id="UW102"><span class="c_rank">2</span><span class="c_id">UW102</span><h3 class="c_name">Finalist 02</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank3"><div id="UW103"><span class="c_rank">3</span><span class="c_id">UW103</span><h3 class="c_name">Finalist 03</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank4"><div id="UW104"><span class="c_rank">4</span><span class="c_id">UW104</span><h3 class="c_name">Finalist 04</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank5"><div id="UW105"><span class="c_rank">5</span><span class="c_id">UW105</span><h3 class="c_name">Finalist 05</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank6"><div id="UW106"><span class="c_rank">6</span><span class="c_id">UW106</span><h3 class="c_name">Finalist 06</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank7"><div id="UW107"><span class="c_rank">7</span><span class="c_id">UW107</span><h3 class="c_name">Finalist 07</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank8"><div id="UW108"><span class="c_rank">8</span><span class="c_id">UW108</span><h3 class="c_name">Finalist 08</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank9"><div id="UW109"><span class="c_rank">9</span><span class="c_id">UW109</span><h3 class="c_name">Finalist 09</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank10"><div id="UW110"><span class="c_rank">10</span><span class="c_id">UW110</span><h3 class="c_name">Finalist 10</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank11"><div id="UW111"><span class="c_rank">11</span><span class="c_id">UW111</span><h3 class="c_name">Finalist 11</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank12"><div id="UW112"><span class="c_rank">12</span><span class="c_id">UW112</span><h3 class="c_name">Finalist 12</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank13"><div id="UW113"><span class="c_rank">13</span><span class="c_id">UW113</span><h3 class="c_name">Finalist 13</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank14"><div id="UW114"><span class="c_rank">14</span><span class="c_id">UW114</span><h3 class="c_name">Finalist 14</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

<div class="climber clearfix" id="rank15"><div id="UW115"><span class="c_rank">15</span><span class="c_id">UW115</span><h3 class="c_name">Finalist 15</h3><span class="c_top badge"><span class="top">0</span>t<span class="topAttempts">0</span></span><span class="c_bonus badge"><span class="bonus">0</span>b<span class="bonusAttempts">0</span></span><div class="c_score"><div class="c_score-col" id="route1">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route2">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route3">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route4">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route5">t<span class="top">0</span> b<span class="bonus">0</span></div><div class="c_score-col" id="route6">t<span class="top">0</span> b<span class="bonus">0</span></div></div></div></div>

</section><?php include('includes/footer.php'); ?>